
import { createClient } from '@supabase/supabase-js';
import { Message, UserProfile } from '../types';

// Credentials injected for instant deployment
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL || "https://ivvglvpnryiwjdqdsvka.supabase.co";
const supabaseAnonKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dmdsdnBucnlpd2pkcWRzdmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMTcxMzEsImV4cCI6MjA4MDY5MzEzMX0.RgQVnTVjptaZTArvv8OvdWxqc7rgnaQaoOhuZH4GtsA";

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials missing! Chat will not work.");
}

export const supabase = createClient(
  supabaseUrl,
  supabaseAnonKey,
  {
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

/* 
  --- SQL SETUP INSTRUCTIONS ---
  Run this in your Supabase SQL Editor to enable Global Meet History:

  create table if not exists global_messages (
    id bigint generated by default as identity primary key,
    content text,
    sender_id text,
    sender_name text,
    sender_profile jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  alter table global_messages disable row level security;

  create table if not exists chat_history (
    id bigint generated by default as identity primary key,
    user_id text not null,
    content text,
    type text not null,
    sender text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  alter table chat_history disable row level security;
*/

// --- GLOBAL MEET FUNCTIONS ---

export const getGlobalMessages = async (): Promise<Message[]> => {
  const { data, error } = await supabase
    .from('global_messages')
    .select('*')
    .order('created_at', { ascending: false }) // Get newest first
    .limit(50);

  if (error) {
    console.error("Error fetching global messages:", error);
    return [];
  }

  // Convert to Message type and reverse to show oldest -> newest
  return (data || []).reverse().map((row: any) => ({
    id: row.id.toString(),
    text: row.content,
    sender: 'stranger', // We calculate 'me' vs 'stranger' in the hook
    senderName: row.sender_name,
    senderPeerId: row.sender_id,
    senderProfile: row.sender_profile,
    timestamp: new Date(row.created_at).getTime(),
    type: 'text'
  }));
};

export const insertGlobalMessage = async (text: string, userProfile: UserProfile, peerId?: string) => {
  const { error } = await supabase.from('global_messages').insert({
    content: text,
    sender_id: peerId || 'unknown',
    sender_name: userProfile.username,
    sender_profile: userProfile
  });

  if (error) {
    console.error("Error sending global message:", error);
    throw error;
  }
};

// --- HISTORY FUNCTIONS ---

export const saveMessageToHistory = async (userId: string, message: Message) => {
  // Only save text messages for history to save bandwidth/storage
  if (message.type !== 'text') return;

  const { error } = await supabase.from('chat_history').insert({
    user_id: userId,
    content: message.text,
    type: message.type,
    sender: message.sender,
    created_at: new Date(message.timestamp).toISOString()
  });

  if (error) console.error("Failed to save history:", error);
};

export const fetchChatHistory = async (userId: string): Promise<Message[]> => {
  const { data, error } = await supabase
    .from('chat_history')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: true })
    .limit(50);

  if (error || !data) return [];

  return data.map((row: any) => ({
    id: row.id.toString(),
    text: row.content,
    type: row.type as 'text',
    sender: row.sender as 'me' | 'stranger' | 'system',
    timestamp: new Date(row.created_at).getTime()
  }));
};
