
import { createClient } from '@supabase/supabase-js';
import { Message, UserProfile } from '../types';

// Credentials injected for instant deployment
const supabaseUrl = (import.meta as any).env.VITE_SUPABASE_URL || "https://ivvglvpnryiwjdqdsvka.supabase.co";
const supabaseAnonKey = (import.meta as any).env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dmdsdnBucnlpd2pkcWRzdmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMTcxMzEsImV4cCI6MjA4MDY5MzEzMX0.RgQVnTVjptaZTArvv8OvdWxqc7rgnaQaoOhuZH4GtsA";

if (!supabaseUrl || !supabaseAnonKey) {
  console.warn("Supabase credentials missing! Chat will not work.");
}

export const supabase = createClient(
  supabaseUrl,
  supabaseAnonKey,
  {
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

/* 
  --- GLOBAL MEET SQL ---
  Run this if you want history to work:

  create table if not exists global_messages (
    id bigint generated by default as identity primary key,
    content text not null,
    sender_id text not null,
    sender_name text not null,
    sender_profile jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );
  alter table global_messages disable row level security;
  
  -- History for 1:1
  create table if not exists chat_history (
    id bigint generated by default as identity primary key,
    user_id text not null,
    content text,
    type text not null,
    sender text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );
  alter table chat_history disable row level security;
*/

// --- GLOBAL MEET FUNCTIONS ---

export const getGlobalMessages = async (): Promise<any[]> => {
  try {
    const { data, error } = await supabase
      .from('global_messages')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(50);

    if (error) {
      // Table likely missing, return empty to allow app to function
      console.warn("History fetch failed (likely no table):", error.message);
      return [];
    }
    return data || [];
  } catch (err) {
    return [];
  }
};

export const insertGlobalMessage = async (text: string, userProfile: UserProfile, peerId: string) => {
  // We throw error here so the hook handles the fallback
  const { error } = await supabase.from('global_messages').insert({
    content: text,
    sender_id: peerId,
    sender_name: userProfile.username,
    sender_profile: userProfile
  });

  if (error) {
    throw new Error(error.message);
  }
};

// --- 1-on-1 HISTORY FUNCTIONS ---

export const saveMessageToHistory = async (userId: string, message: Message) => {
  if (message.type !== 'text') return; 
  
  // Fire and forget, don't block UI
  const { error } = await supabase.from('chat_history').insert({
    user_id: userId,
    content: message.text,
    type: message.type,
    sender: message.sender,
    created_at: new Date(message.timestamp).toISOString()
  });

  if (error) {
    console.warn("Save history failed:", error);
  }
};

export const fetchChatHistory = async (userId: string): Promise<Message[]> => {
  try {
    const { data, error } = await supabase
      .from('chat_history')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: true })
      .limit(50);

    if (error || !data) return [];

    return data.map((row: any) => ({
      id: row.id.toString(),
      text: row.content,
      type: row.type as 'text',
      sender: row.sender as 'me' | 'stranger' | 'system',
      timestamp: new Date(row.created_at).getTime()
    }));
  } catch(e) {
    return [];
  }
};
